### ISSUE TITLE
collaboration with AQP suite of R packages

### ISSUE THREAD

**Issue by dylanbeaudette** [Laboratorio-de-Pedometria/pedometrics-package#2]
Howdy,

Interested in collaborating with the authors of the AQP suite of packages? It could be as simple as cross-referencing documentation and example data, or something more involved.

Cheers,
Dylan

**Comment by samuel-rosa** [comment]
@dylanbeaudette I know its a very late reply. I haven't had the chance to think more deeplly about your proposal. So, I am not sure how this benefits me -- and you. I have been extremely busy with undergrad teaching. This has left very little time to work on the R packages. Sorry to disappoint you. :-(

**Comment by dylanbeaudette** [comment]
No problem. Let me know if you would like tighter integration with the `SoilProfileCollection` class. This has been an important foundation in the AQP suite of packages for nearly 10 years. CC-ing @pierreroudier so that he is in the loop. AQP now lives here: https://github.com/ncss-tech
